set file_list [list "./hardware/include/pu_controller_bin.vh" \
"./hardware/include/common.vh" \
"./hardware/include/rd_mem_controller.vh" \
"./hardware/include/wr_mem_controller.vh" \
"./hardware/source/top/zynq_wrapper.v" \
"./hardware/source/axi_master/axi_master.v" \
"./hardware/source/axi_master_wrapper/axi_master_wrapper.v" \
"./hardware/source/axi_master/wburst_counter.v" \
"./hardware/source/primitives/FIFO/fifo.v" \
"./hardware/source/primitives/FIFO/fifo_fwft.v" \
"./hardware/source/primitives/FIFO/xilinx_bram_fifo.v" \
"./hardware/source/primitives/ROM/ROM.v" \
"./hardware/source/axi_slave/axi_slave.v" \
"./hardware/source/dnn_accelerator/dnn_accelerator.v" \
"./hardware/source/dnn_accelerator/dnn_accelerator_4AXI.v" \
"./hardware/source/mem_controller/mem_controller.v" \
"./hardware/source/mem_controller/mem_controller_top.v" \
"./hardware/source/mem_controller/mem_controller_top_4AXI.v" \
"./hardware/source/primitives/MACC/multiplier.v" \
"./hardware/source/primitives/MACC/macc.v" \
"./hardware/source/primitives/COUNTER/counter.v" \
"./hardware/source/PU/PU.v" \
"./hardware/source/PE/PE.v" \
"./hardware/source/primitives/REGISTER/register.v" \
"./hardware/source/normalization/normalization.v" \
"./hardware/source/primitives/PISO/piso.v" \
"./hardware/source/primitives/PISO/piso_norm.v" \
"./hardware/source/primitives/SIPO/sipo.v" \
"./hardware/source/pooling/pooling.v" \
"./hardware/source/primitives/COMPARATOR/comparator.v" \
"./hardware/source/primitives/MUX/mux_2x1.v" \
"./hardware/source/PE_buffer/PE_buffer.v" \
"./hardware/source/primitives/lfsr/lfsr.v" \
"./hardware/source/vectorgen/vectorgen.v" \
"./hardware/source/PU/PU_controller.v" \
"./hardware/source/weight_buffer/weight_buffer.v" \
"./hardware/source/primitives/RAM/ram.v" \
"./hardware/source/data_packer/data_packer.v" \
"./hardware/source/data_unpacker/data_unpacker.v" \
"./hardware/source/activation/activation.v" \
"./hardware/source/read_info/read_info.v" \
"./hardware/source/buffer_read_counter/buffer_read_counter.v" \
"./hardware/source/loopback/loopback_top.v" \
"./hardware/source/loopback/loopback.v" \
"./hardware/source/loopback_pu_controller/loopback_pu_controller_top.v" \
"./hardware/source/loopback_pu_controller/loopback_pu_controller.v" \
"./hardware/source/serdes/serdes.v" ]
