# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.cache/wt [current_project]
set_property parent.project_path /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.2 [current_project]
set_property ip_output_repo /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/include/common.vh
read_verilog -library xil_defaultlib {
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/PE/PE.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/PU/PU.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/PU/PU_controller.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/ROM/ROM.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/activation/activation.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/axi_master/axi_master.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/axi_master_wrapper/axi_master_wrapper.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/axi_slave/axi_slave.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/buffer_read_counter/buffer_read_counter.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/COUNTER/counter.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/data_packer/data_packer.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/data_unpacker/data_unpacker.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/dnn_accelerator/dnn_accelerator.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/FIFO/fifo.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/FIFO/fifo_fwft.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/MACC/macc.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/mem_controller/mem_controller.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/mem_controller/mem_controller_top.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/MACC/multiplier.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/normalization/normalization.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/PISO/piso_norm.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/pooling/pooling.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/RAM/ram.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/read_info/read_info.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/REGISTER/register.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/serdes/serdes.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/primitives/SIPO/sipo.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/vectorgen/vectorgen.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/axi_master/wburst_counter.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/weight_buffer/weight_buffer.v
  /home/omar/Drive2/Work/dnnweaver.public/fpga/hardware/source/top/zynq_wrapper.v
}
add_files /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/zc702.bd
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/ip/zc702_processing_system7_1_0/zc702_processing_system7_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/ip/zc702_rst_processing_system7_1_50M_0/zc702_rst_processing_system7_1_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/ip/zc702_rst_processing_system7_1_50M_0/zc702_rst_processing_system7_1_50M_0.xdc]
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/ip/zc702_rst_processing_system7_1_50M_0/zc702_rst_processing_system7_1_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/ip/zc702_auto_pc_0/zc702_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/zc702_ooc.xdc]
set_property is_locked true [get_files /home/omar/Drive2/Work/dnnweaver.public/fpga/vivado/dnnweaver.srcs/sources_1/bd/zc702/zc702.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zynq_wrapper -part xc7z020clg484-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef zynq_wrapper.dcp

catch { report_utilization -file zynq_wrapper_utilization_synth.rpt -pb zynq_wrapper_utilization_synth.pb }
